### ISSUE TITLE
Explorer summaries are still not updating properly

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#166]
I have an Explorer instance where there has been a fair amount of data filling happening. The summary doesn't reflect the filling that has happened. I'm concerned that the summary process is still not refreshing properly, despite the `--force-refresh ` flag and process.

Example summary:
![image](https://user-images.githubusercontent.com/3445853/88609796-5a956c00-d0c8-11ea-9029-40a2eb15cfef.png)

And a table of dates from examining files that should be in the index:
```
18-09    37562
18-10    39844
18-11    37623
18-12    39412
19-01    40128
19-02    36573
19-03    39695
19-04    38556
19-05    38031
19-06    37592
19-07    39162
19-08    39361
19-09    36668
19-10    38094
19-11    36480
19-12    39250
20-01    38971
20-02    36435
20-03    39827
20-04    38486
20-05    38213
20-06    31341
```

The table shows that there are a consistent number of scenes over the months in 2020, but that is not reflected in the summary graph.

**Comment by alexgleith** [comment]
Having said that, looks like it could be the datacube index...

```
20-1 has 39111 scenes
20-2 has 36513 scenes
20-3 has 39919 scenes
20-4 has 38558 scenes
20-5 has 38218 scenes
20-6 has 35173 scenes
20-7 has 27311 scenes
```

this is from my datacube

**Comment by alexgleith** [comment]
```
20-01    39186
20-02    36597
20-03    40013
20-04    38654
20-05    38294
20-06    35363
20-07    26023
```

And this is from the latest inventory. I think it's actually not that different... though there seems to be a systematic difference in counts...

So I do think that Explorer isn't representing what is in the DB.

**Comment by alexgleith** [comment]
More evidence, Explorer says "24,384 datasets for July"

![image](https://user-images.githubusercontent.com/3445853/88615634-b2869f80-d0d5-11ea-803d-c46c0095b658.png)

And 35,175 in June

![image](https://user-images.githubusercontent.com/3445853/88615684-caf6ba00-d0d5-11ea-9339-8e299c7d5b48.png)

**Comment by alexgleith** [comment]
Ok, so after exhaustive auditing, I am confident that the Africa datacube has exactly the data on S3. But Explorer is NOT representing it all.

Any suggestions on how we can make this work properly, other than recreating the Explorer index, @jeremyh?

**Comment by jeremyh** [comment]
@alexgleith Can you slack me a recent full dump of Africa DB?

**Comment by alexgleith** [comment]
Did you get any further with this, @jeremyh?

I'm working with the latest dev code and testing recreating summaries and extents. It's pretty slow, but still doesn't seem to show the data that is missing between ODC and Explorer.

**Comment by jeremyh** [comment]
Not yet; it’s on my list for this release.

**Comment by NikitaGandhi** [comment]
Ran `cubedash-gen --recreate-dataset-extents --force-refresh --all` with latest unstable image - `explorer:2.1.11-166-ga34234b` - and still got bellow error for `s2_l2a`

```
2020-09-24T07:48:32.895281Z [exception] generate.product.error         extents=True force=True product=s2_l2a
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: GEOSUnaryUnion: TopologyException: found non-noded intersection between LINESTRING (319267 2.30004e+06, 319446 2.30004e+06) and LINESTRING (319436 2.30004e+06, 300111 2.22221e+06) at 319435.6852046852 2300039
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/datacube_explorer-2.1.12.dev166+ga34234b-py3.6.egg/cubedash/generate.py", line 96, in generate_report
    force_dataset_extent_recompute=recreate_dataset_extents,
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/datacube_explorer-2.1.12.dev166+ga34234b-py3.6.egg/cubedash/summary/_stores.py", line 241, in refresh_product
    self._refresh_product_regions(product)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/datacube_explorer-2.1.12.dev166+ga34234b-py3.6.egg/cubedash/summary/_stores.py", line 275, in _refresh_product_regions
    dataset_type.id,
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2244, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1012, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1187, in _execute_text
    parameters,
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) GEOSUnaryUnion: TopologyException: found non-noded intersection between LINESTRING (319267 2.30004e+06, 319446 2.30004e+06) and LINESTRING (319436 2.30004e+06, 300111 2.22221e+06) at 319435.6852046852 2300039
[SQL:
        with srid_groups as (
             select cubedash.dataset_spatial.dataset_type_ref                         as dataset_type_ref,
                     cubedash.dataset_spatial.region_code                             as region_code,
                     ST_Transform(ST_Union(cubedash.dataset_spatial.footprint), 4326) as footprint,
                     count(*)                                                         as count
              from cubedash.dataset_spatial
              where cubedash.dataset_spatial.dataset_type_ref = %s
              group by cubedash.dataset_spatial.dataset_type_ref,
                       cubedash.dataset_spatial.region_code,
                       st_srid(cubedash.dataset_spatial.footprint)
        )
        insert into cubedash.region (dataset_type_ref, region_code, footprint, count)
            select srid_groups.dataset_type_ref,
                   coalesce(srid_groups.region_code, '')                          as region_code,
                   ST_SimplifyPreserveTopology(
                           ST_Union(ST_Buffer(srid_groups.footprint, 0)), 0.0001) as footprint,
                   sum(srid_groups.count)                                         as count
            from srid_groups
            group by srid_groups.dataset_type_ref, srid_groups.region_code
        on conflict (dataset_type_ref, region_code)
            do update set count           = excluded.count,
                          generation_time = now(),
                          footprint       = excluded.footprint
            ]
[parameters: (22,)]
(Background on this error at: http://sqlalche.me/e/2j85)
s2_l2a error (see log)

done. 17/18 generated, 1 failures
```

**Comment by pindge** [comment]
```
ows_dev_12102020=> select id from agdc.dataset_type where name='s2a_nrt_granule'
;
 id  
-----
 379
(1 row)
ows_dev_12102020=> select count(*) from agdc.dataset where dataset_type_ref = 379;
 count 
-------
 20408
(1 row)
```
```
[2020-10-16 01:22:58,387] {{pod_launcher.py:141}} INFO - Event: explorer-summary-06c5d7bc7c67451fb06f1d1cf8ac3793 had an event of type Pending
[2020-10-16 01:22:59,395] {{pod_launcher.py:141}} INFO - Event: explorer-summary-06c5d7bc7c67451fb06f1d1cf8ac3793 had an event of type Pending
[2020-10-16 01:23:00,405] {{pod_launcher.py:141}} INFO - Event: explorer-summary-06c5d7bc7c67451fb06f1d1cf8ac3793 had an event of type Running
[2020-10-16 01:23:01,575] {{pod_launcher.py:124}} INFO - b'/env/lib/python3.6/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.\n'
[2020-10-16 01:23:01,575] {{pod_launcher.py:124}} INFO - b'  "Flask-Caching: CACHE_TYPE is set to null, "\n'
[2020-10-16 01:23:01,575] {{pod_launcher.py:124}} INFO - b"Updating 1 products for LocalConfig<loaded_from=defaults, environment='default', config={'db_hostname': 'db-aurora-dea-dev-eks.cluster-cxhoeczwhtar.ap-southeast-2.rds.amazonaws.com', 'db_database': 'ows_dev_12102020', 'db_username': 'explorer_writer', 'db_password': '***', 'index_driver': 'default', 'db_connection_timeout': '60'}>\n"
[2020-10-16 01:23:01,575] {{pod_launcher.py:124}} INFO - b'Generating product summaries...\n'
[2020-10-16 01:23:22,503] {{pod_launcher.py:124}} INFO - b's2a_nrt_granule done: (258 datasets)\n'
[2020-10-16 01:23:22,515] {{pod_launcher.py:124}} INFO - b'done. 1/1 generated, 0 failures\n'
```

**Comment by pindge** [comment]
```
TopologyException: found non-noded intersection between LINESTRING (-1.83528e+06 -3.20299e+06, -1.83533e+06 -3.2026e+06) and LINESTRING (-1.834e+06 -3.2115e+06, -1.83531e+06 -3.20279e+06) at -1835299.7159600947 -3202834.6089869151
{"event":"summary.footprint.union","exception":"Traceback (most recent call last):\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_model.py\", line 99, in add_periods\n    if with_valid_geometries\n  File \"/env/lib/python3.6/site-packages/shapely/ops.py\", line 154, in unary_union\n    return geom_factory(lgeos.methods['unary_union'](collection))\n  File \"/env/lib/python3.6/site-packages/shapely/geometry/base.py\", line 78, in geom_factory\n    raise ValueError(\"No Shapely geometry can be created from null value\")\nValueError: No Shapely geometry can be created from null value","level":"warning","timestamp":"2020-11-10T06:56:45.413957Z"}
```

**Comment by pindge** [comment]
Cannot replicate
