### ISSUE TITLE
Clearly specify DB ROLE (non-superuser) required to run explorer migrations

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#168]
We have some self-learnt explorer roles which are used to run the application. These fail to function for schema migrations. Clearly specify role needed to run schema migration.

```
Initialising schema
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for schema cubedash


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/explorer/bin/cubedash-gen", line 33, in <module>
    sys.exit(load_entry_point('datacube-explorer', 'console_scripts', 'cubedash-gen')())
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/datacube/ui/click.py", line 196, in new_func
    return f(parsed_config, *args, **kwargs)
  File "/home/ubuntu/datacube-explorer/cubedash/generate.py", line 174, in cli
    store.init()
  File "/home/ubuntu/datacube-explorer/cubedash/summary/_stores.py", line 128, in init
    _schema.create_schema(self._engine)
  File "/home/ubuntu/datacube-explorer/cubedash/summary/_schema.py", line 268, in create_schema
    """
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2238, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1006, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_text
    parameters,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema cubedash

[SQL: 
        create unique index if not exists mv_spatial_ref_sys_srid_idx on
            cubedash.mv_spatial_ref_sys(srid);
        ]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

and 

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/explorer/bin/cubedash-gen", line 33, in <module>
    sys.exit(load_entry_point('datacube-explorer', 'console_scripts', 'cubedash-gen')())
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/explorer/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/datacube/ui/click.py", line 196, in new_func
    return f(parsed_config, *args, **kwargs)
  File "/home/ubuntu/datacube-explorer/cubedash/generate.py", line 174, in cli
    store.init()
  File "/home/ubuntu/datacube-explorer/cubedash/summary/_stores.py", line 128, in init
    _schema.create_schema(self._engine)
  File "/home/ubuntu/datacube-explorer/cubedash/summary/_schema.py", line 251, in create_schema
    engine.execute(DDL(f"create schema if not exists {CUBEDASH_SCHEMA}"))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2238, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1076, in _execute_ddl
    compiled,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for database ows

[SQL: create schema if not exists cubedash]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by whatnick** [comment]
Here is the hand crafted explorer role. Would appreciate review and consolidation of these role:
- Schema Migrations Role
- Cubedash Summary Refresh / Creation Role
- Explorer web application role / Read-only

```
# Create cubedash schema if it does not exist
echo "Give explorer schema creation priviledge"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "GRANT CREATE ON DATABASE $DB_NAME TO explorer;"
echo "Creating cubedash schema"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "CREATE SCHEMA IF NOT EXISTS cubedash;"
echo "Update OWNERSHIP if schema already exists"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER SCHEMA cubedash OWNER TO explorer;"

# Add explorer in read only mode to Datacube Core AGDC schema
# Reference: https://www.postgresql.org/docs/9.0/sql-grant.html
echo "Granting read-only access to agdc schema"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "GRANT USAGE ON SCHEMA agdc TO explorer;"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "GRANT SELECT ON ALL TABLES IN SCHEMA agdc TO explorer;"


# TODO: Make conditional on Explorer already being deployed and these tables existing
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER TABLE cubedash.dataset_spatial OWNER TO explorer;"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER TABLE cubedash.product OWNER TO explorer;"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER TABLE cubedash.time_overview OWNER TO explorer;"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER SEQUENCE cubedash.product_id_seq OWNER TO explorer;"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER MATERIALIZED VIEW cubedash.mv_dataset_spatial_quality OWNER TO explorer;"
psql -h $DB_HOSTNAME -p $DB_PORT --username $DB_USERNAME -d $DB_NAME -c "ALTER MATERIALIZED VIEW cubedash.mv_spatial_ref_sys OWNER TO explorer;"
```
