### ISSUE TITLE
Post-union geometry errors should be handled more cleanly

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#172]
Error posted by @whatnick on Slack, from an Africa generate failure:
```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: GEOSUnaryUnion: TopologyException: Input geom 0 is invalid: Self-intersection at or near point -13943223.526815126 -4216248.3542871606 at -13943223.526815126 -4216248.3542871606


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/cubedash/generate.py", line 50, in generate_report
    updated = store.get_or_update(product.name, None, None, None, force_refresh)
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 569, in get_or_update
    force_refresh=True,
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 611, in update
    for year_ in years
  File "/env/lib/python3.6/site-packages/cubedash/summary/_model.py", line 62, in add_periods
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/env/lib/python3.6/site-packages/cubedash/summary/_model.py", line 62, in <listcomp>
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 611, in <genexpr>
    for year_ in years
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 569, in get_or_update
    force_refresh=True,
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 602, in update
    for month_ in range(1, 13)
  File "/env/lib/python3.6/site-packages/cubedash/summary/_model.py", line 62, in add_periods
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/env/lib/python3.6/site-packages/cubedash/summary/_model.py", line 62, in <listcomp>
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 602, in <genexpr>
    for month_ in range(1, 13)
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 569, in get_or_update
    force_refresh=True,
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 597, in update
    product_name, _utils.as_time_range(year, month)
  File "/env/lib/python3.6/site-packages/cubedash/summary/_summarise.py", line 78, in calculate_summary
    func.now().label("summary_gen_time"),
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2244, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) GEOSUnaryUnion: TopologyException: Input geom 0 is invalid: Self-intersection at or near point -13943223.526815126 -4216248.3542871606 at -13943223.526815126 -4216248.3542871606

[SQL: SELECT sum(srid_summaries.dataset_count) AS dataset_count, array_agg(srid_summaries.srid) AS srids, sum(srid_summaries.size_bytes) AS size_bytes, ST_AsEWKB(ST_Union(srid_summaries.footprint_geometry)) AS footprint_geometry, max(srid_summaries.newest_dataset_creation_time) AS newest_dataset_creation_time, now() AS summary_gen_time 
FROM (SELECT ST_SRID(cubedash.dataset_spatial.footprint) AS srid, count(*) AS dataset_count, ST_Transform(ST_Union(cubedash.dataset_spatial.footprint), %(ST_Transform_1)s) AS footprint_geometry, sum(cubedash.dataset_spatial.size_bytes) AS size_bytes, max(cubedash.dataset_spatial.creation_time) AS newest_dataset_creation_time 
FROM cubedash.dataset_spatial 
WHERE (tstzrange(%(tstzrange_1)s, %(tstzrange_2)s, %(tstzrange_3)s) @> cubedash.dataset_spatial.center_time) AND cubedash.dataset_spatial.dataset_type_ref = (SELECT agdc.dataset_type.id 
FROM agdc.dataset_type 
WHERE agdc.dataset_type.name = %(name_1)s) GROUP BY srid) AS srid_summaries]
[parameters: {'ST_Transform_1': 3577, 'tstzrange_1': datetime.datetime(2017, 10, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin')), 'tstzrange_2': datetime.datetime(2017, 11, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin')), 'tstzrange_3': '[]', 'name_1': 's2_l2a'}]
(Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by whatnick** [comment]
Related to #146

**Comment by jeremyh** [comment]
We're now buffering on union to catch above issue. See linked commits. Closing unless we see this again.
