### ISSUE TITLE
Prometheus Metrics Regression due to new code merge

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#184]
There are errors in prometheus metrics endpoints due to latest development:

```
AssertionError: View function mapping is overwriting an existing endpoint function: prometheus_metrics
    "existing endpoint function: %s" % endpoint
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1284, in add_url_rule
    return f(self, *args, **kwargs)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 98, in wrapper_func
    self.add_url_rule(rule, endpoint, f, **options)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1315, in decorator
    @self.do_not_track()
  File "/env/lib/python3.6/site-packages/prometheus_flask_exporter/__init__.py", line 252, in register_endpoint
    self.register_endpoint(path)
  File "/env/lib/python3.6/site-packages/prometheus_flask_exporter/multiprocess.py", line 186, in __init__
    metrics = GunicornInternalPrometheusMetrics(app)
  File "/env/lib/python3.6/site-packages/cubedash/_model.py", line 278, in enable_prometheus
    func()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    self.try_trigger_before_first_request_functions()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1945, in full_dispatch_request
    response = self.full_dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
Traceback (most recent call last):
[2020-09-10 05:35:38,664] ERROR in app: Exception on /metrics [GET]
```

**Comment by whatnick** [comment]
Could not reproduce.
