### ISSUE TITLE
Operation on mixed SRID geometries on products that used to work

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#186]
What I did:

- Fresh backup of the DE Africa DB
- Restore entire DB
- Delete `cubedash` schema
- Create new schema
- Run `cubedash-gen --all`

A number of products break with similar errors to below:

```
2020-09-17T03:51:44.394947Z [exception] generate.product.error         extents=False force=False product=ga_ls8c_wofs_2
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: Operation on mixed SRID geometries


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/cubedash/generate.py", line 96, in generate_report
    force_dataset_extent_recompute=recreate_dataset_extents,
  File "/code/cubedash/summary/_stores.py", line 241, in refresh_product
    self._refresh_product_regions(product)
  File "/code/cubedash/summary/_stores.py", line 273, in _refresh_product_regions
    dataset_type.id,
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2237, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) Operation on mixed SRID geometries

[SQL: 
        with srid_groups as (
             select cubedash.dataset_spatial.dataset_type_ref                        as dataset_type_ref,
                     cubedash.dataset_spatial.region_code                             as region_code,
                     ST_Transform(ST_Union(cubedash.dataset_spatial.footprint), 4326) as footprint,
                     count(*)                                                         as count
              from cubedash.dataset_spatial
              where cubedash.dataset_spatial.dataset_type_ref = %s
              group by cubedash.dataset_spatial.dataset_type_ref, cubedash.dataset_spatial.region_code
        )
        insert into cubedash.region (dataset_type_ref, region_code, footprint, count)
            select srid_groups.dataset_type_ref,
                   coalesce(srid_groups.region_code, '')                          as region_code,
                   ST_SimplifyPreserveTopology(
                           ST_Union(ST_Buffer(srid_groups.footprint, 0)), 0.0001) as footprint,
                   sum(srid_groups.count)                                         as count
            from srid_groups
            group by srid_groups.dataset_type_ref, srid_groups.region_code
        on conflict (dataset_type_ref, region_code)
            do update set count           = excluded.count,
                          generation_time = now(),
                          footprint       = excluded.footprint

            ]
[parameters: (15,)]
(Background on this error at: http://sqlalche.me/e/13/2j85)
ga_ls8c_wofs_2 error (see log)
```

**Comment by alexgleith** [comment]
The above issue happens on the following products:

```
ga_ls8c_wofs_2
ls_usgs_wofs_scene
ls_usgs_fc_scene
ls7_usgs_sr_scene
ls8_usgs_sr_scene
ls5_usgs_sr_scene
```

**Comment by jeremyh** [comment]
My Africa clone seems to be too old to reproduce this, as a rerun of those steps has worked. 

Presumably Africa now has datasets with identical region codes but different CRSes, and we're missing this in Explorer's current test data.

**Comment by alexgleith** [comment]
See the PR for the fix. I dropped and recreated the Explorer schema, which may be different to your environment?

But yeah, your intuition is right :-)

**Comment by jeremyh** [comment]
Yeah, that's what I did too, just now

```
cubedash-gen --drop
cubedash-gen --init --all
```

**Comment by jeremyh** [comment]
Thanks for the fix. I'll add it to the (...long) list to add test data for the case.
