### ISSUE TITLE
Invalid dates in URLs can cause exceptions to be thrown

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#221]
![image](https://user-images.githubusercontent.com/24644475/99016418-32fcdd80-25ab-11eb-80bc-b0b9e289b9e9.png)
![image](https://user-images.githubusercontent.com/24644475/99016482-52940600-25ab-11eb-8934-b49da27f7c4b.png)
![image](https://user-images.githubusercontent.com/24644475/99016512-60e22200-25ab-11eb-942e-72c17dbefceb.png)

```
ValueError
ValueError: month must be in 1..12

Traceback (most recent call last)
File "/env/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/env/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
return self.app(environ, start_response)
File "/env/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/env/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/code/cubedash/_pages.py", line 56, in overview_page
) = _load_product(product_name, year, month, day)
File "/code/cubedash/_pages.py", line 249, in _load_product
time_summary = _model.get_time_summary(product_name, year, month, day)
File "/env/lib/python3.6/site-packages/flask_caching/__init__.py", line 907, in decorated_function
rv = f(*args, **kwargs)
File "/code/cubedash/_model.py", line 75, in get_time_summary
return STORE.get(product_name, year, month, day)
File "/code/cubedash/summary/_stores.py", line 479, in get
start_day, period = self._start_day(year, month, day)
File "/code/cubedash/summary/_stores.py", line 509, in _start_day
return date(year or 1900, month or 1, day or 1), period
ValueError: month must be in 1..12
```

**Comment by jeremyh** [comment]
This is when the user manually creates a URL out of range?

Example: https://explorer.dea.ga.gov.au/ls5_fc_albers/2020/15

I assume the "correct" behaviour would be a 404 page.

**Comment by omad** [comment]
I don't think this is worth keeping open as an issue to fix.

While we could have special handling for every type of invalid URL, I don't think calling this one out as special is necessary.

In production deployments an example URL and error page looks like:

![image](https://user-images.githubusercontent.com/108979/181700256-15aaec91-c144-4149-b8fd-e19d96a5e84c.png)
