### ISSUE TITLE
update fails for s2_l2a due to non-noded LINESTRING

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#251]
```
root@31bc5c5a68d7:/code# cubedash-gen --refresh-stats --no-init-database --force-refresh s2_l2a
/env/lib/python3.6/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Updating 1 products for LocalConfig<loaded_from=defaults, environment='default', config={'db_hostname': 'postgres', 'db_port': '5432', 'db_database': 'opendatacube', 'db_username': 'opendatacubeusername', 'db_password': '***', 'index_driver': 'default', 'db_connection_timeout': '60'}>
Generating product summaries...
TopologyException: found non-noded intersection between LINESTRING (-1.45781e+07 -4.03415e+06, -1.45781e+07 -4.03415e+06) and LINESTRING (-1.45781e+07 -4.03415e+06, -1.45781e+07 -4.03415e+06) at -14578142.270017713 -4034148.8940197057
2020-12-17T04:03:41.554430Z [warning  ] summary.footprint.union        
Traceback (most recent call last):
  File "/code/cubedash/summary/_model.py", line 99, in add_periods
    if with_valid_geometries
  File "/env/lib/python3.6/site-packages/shapely/ops.py", line 154, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
TopologyException: found non-noded intersection between LINESTRING (-1.65441e+07 -8.21965e+06, -1.65441e+07 -8.21965e+06) and LINESTRING (-1.65441e+07 -8.21965e+06, -1.65441e+07 -8.21965e+06) at -16544077.929609459 -8219654.2669721693
2020-12-17T04:03:46.295454Z [exception] generate.product.error         extents=False force=True product=s2_l2a
Traceback (most recent call last):
  File "/code/cubedash/summary/_model.py", line 99, in add_periods
    if with_valid_geometries
  File "/env/lib/python3.6/site-packages/shapely/ops.py", line 154, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/cubedash/generate.py", line 101, in generate_report
    updated = store.get_or_update(product.name, force_refresh=force_refresh)
  File "/code/cubedash/summary/_stores.py", line 961, in get_or_update
    force_refresh=True,
  File "/code/cubedash/summary/_stores.py", line 1003, in update
    for year_ in years
  File "/code/cubedash/summary/_model.py", line 60, in add_periods
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/code/cubedash/summary/_model.py", line 60, in <listcomp>
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/code/cubedash/summary/_stores.py", line 1003, in <genexpr>
    for year_ in years
  File "/code/cubedash/summary/_stores.py", line 961, in get_or_update
    force_refresh=True,
  File "/code/cubedash/summary/_stores.py", line 994, in update
    for month_ in range(1, 13)
  File "/code/cubedash/summary/_model.py", line 111, in add_periods
    if with_valid_geometries
  File "/env/lib/python3.6/site-packages/shapely/ops.py", line 154, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
s2_l2a error (see log)
```

**Comment by pindge** [comment]
```
2020-12-18T01:35:55.455387Z [exception] generate.product.error         extents=False force=True product=s2_l2a
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: GEOSUnaryUnion: TopologyException: found non-noded intersection between LINESTRING (319267 2.30004e+06, 319446 2.30004e+06) and LINESTRING (319436 2.30004e+06, 309326 2.25947e+06) at 319435.66269497614 2300039


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/cubedash/generate.py", line 96, in generate_report
    force_dataset_extent_recompute=recreate_dataset_extents,
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 268, in refresh_product
    self._refresh_product_regions(product)
  File "/env/lib/python3.6/site-packages/cubedash/summary/_stores.py", line 304, in _refresh_product_regions
    dataset_type.id,
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) GEOSUnaryUnion: TopologyException: found non-noded intersection between LINESTRING (319267 2.30004e+06, 319446 2.30004e+06) and LINESTRING (319436 2.30004e+06, 309326 2.25947e+06) at 319435.66269497614 2300039

[SQL: 
        with srid_groups as (
             select cubedash.dataset_spatial.dataset_type_ref                         as dataset_type_ref,
                     cubedash.dataset_spatial.region_code                             as region_code,
                     ST_Transform(ST_Union(cubedash.dataset_spatial.footprint), 4326) as footprint,
                     count(*)                                                         as count
              from cubedash.dataset_spatial
              where cubedash.dataset_spatial.dataset_type_ref = %s
                    and
                    st_isvalid(cubedash.dataset_spatial.footprint)
              group by cubedash.dataset_spatial.dataset_type_ref,
                       cubedash.dataset_spatial.region_code,
                       st_srid(cubedash.dataset_spatial.footprint)
        )
        insert into cubedash.region (dataset_type_ref, region_code, footprint, count)
            select srid_groups.dataset_type_ref,
                   coalesce(srid_groups.region_code, '')                          as region_code,
                   ST_SimplifyPreserveTopology(
                           ST_Union(ST_Buffer(srid_groups.footprint, 0)), 0.0001) as footprint,
                   sum(srid_groups.count)                                         as count
            from srid_groups
            group by srid_groups.dataset_type_ref, srid_groups.region_code
        on conflict (dataset_type_ref, region_code)
            do update set count           = excluded.count,
                          generation_time = now(),
                          footprint       = excluded.footprint

            ]
[parameters: (22,)]
(Background on this error at: http://sqlalche.me/e/13/2j85)
s2_l2a error (see log)
done. 0/1 generated, 1 failures
Refreshing statistics...done
```

**Comment by pindge** [comment]
@jeremyh, I have searched everywhere in the database, no footprint is a LINESTRING, everything is a polygon or multipolygon and I have even run st_dump for multipolygon and non contains LINESTRING.

I searched in dataset_spatial footprint, region footprint and time_overview footprint_geometry. NO TRACE of LINESTRING.

I am out of ideas.

**Comment by alexgleith** [comment]
It happens after doing some unions.

The way I've found out where it happens is by getting the failing summary query and slowly making it smaller and smaller until you find just a small area that triggers it.

It's so hard!

**Comment by pindge** [comment]
```
africa=# select id, name from agdc.dataset_type
africa-# ;
 id |             name
----+-------------------------------
  1 | ls8_usgs_sr_scene
  3 | ls5_usgs_sr_scene
  5 | ls_usgs_wofs_scene
  6 | ls_usgs_fc_scene
 13 | ga_ls8c_wofs_2_annual_summary
 12 | srtm
 14 | alos_palsar_mosaic
 11 | ls_usgs_wofs_summary
 15 | ga_ls8c_wofs_2
 16 | ga_ls8c_wofs_2_summary
 17 | ga_ls8c_gm_2_annual
 18 | sentinel1_ghana_monthly
 19 | s2a_msil2a
 20 | s2b_msil2a
 21 | jers_sar_tile
  2 | ls7_usgs_sr_scene
 22 | s2_l2a
 23 | ga_s2_clear_pixel_count
 24 | ga_s2_gm
(19 rows)

africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 12;
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 1;
ERROR:  Operation on mixed SRID geometries
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 2;
ERROR:  Operation on mixed SRID geometries
africa=# ^C
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 3;
ERROR:  Operation on mixed SRID geometries
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 6;
ERROR:  Operation on mixed SRID geometries
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 13;
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 14;
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref = 21;
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref =241;
 st_astext
-----------

(1 row)

africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref =24;
africa=# select st_astext(st_transform(st_union(footprint), 4326)) from cubedash.dataset_spatial where dataset_type_ref =22;
ERROR:  Operation on mixed SRID geometries

```

**Comment by pindge** [comment]
```
africa=# select st_srid(footprint) as srid, left(st_astext(st_union(footprint)), 30) from cubedash.dataset_spatial where dataset_type_ref = 22 group by srid;
 srid  |              left
-------+--------------------------------
 32626 | POLYGON((601512.489648439 1490
 32627 | POLYGON((236384.201010266 1537
 32628 | POLYGON((909779 552808.8790453
 32629 | POLYGON((853508.527362645 3130
 32630 | POLYGON((762971.647852416 3899
 32631 | POLYGON((379763.136252876 3952
 32632 | POLYGON((199981 -9779,199981 1
 32633 | POLYGON((199981 -6899,199981 7
 32634 | POLYGON((786483.668185872 -977
 32635 | POLYGON((896463.06194222 -9779
 32636 | POLYGON((664151.641414694 -977
 32637 | POLYGON((787480.55367227 -9779
 32638 | POLYGON((909779 90138.65460134
 32639 | POLYGON((289526.701316201 7737
 32730 | MULTIPOLYGON(((467331.75969711
 32731 | POLYGON((909779 9862705,804342
 32732 | MULTIPOLYGON(((809759 6966763.
 32733 | POLYGON((809759 6090985.675866
 32734 | POLYGON((667250.464955193 5997
 32735 | POLYGON((594746.569420837 6069
 32736 | MULTIPOLYGON(((809759 4757607.
 32737 | MULTIPOLYGON(((524768 4717367,
 32738 | MULTIPOLYGON(((199981 9183456.
 32739 | MULTIPOLYGON(((909779 7609864.
 32740 | MULTIPOLYGON(((585341.00000000
```

**Comment by pindge** [comment]
```
    @classmethod
    def add_periods(
        cls,
        periods: Iterable["TimePeriodOverview"],
        # This is in CRS units. Albers, so 1KM.
        # Lower value will have a more accurate footprint and much larger page load times.
        footprint_tolerance=1000.0,
    ):
        print(periods)
        periods = [p for p in periods if p is not None and p.dataset_count > 0]
        period = "day"
        crses = set(p.footprint_crs for p in periods)
        print(periods)
        exit()
```

```
Generating product summaries...
<generator object SummaryStore.update.<locals>.<genexpr> at 0x7f9b913997d8>
<generator object SummaryStore.update.<locals>.<genexpr> at 0x7f9b91399830>
[TimePeriodOverview(dataset_count=133, timeline_dataset_counts=Counter({datetime.date(2016, 11, 10): 14, datetime.date(2016, 11, 20): 14, datetime.date(2016, 11, 30): 14, datetime.date(2016, 11, 7): 11, datetime.date(2016, 11, 9): 10, datetime.date(2016, 11, 3): 9, datetime.date(2016, 11, 13): 9, datetime.date(2016, 11, 23): 9, datetime.date(2016, 11, 17): 8, datetime.date(2016, 11, 27): 8, datetime.date(2016, 11, 2): 6, datetime.date(2016, 11, 12): 6, datetime.date(2016, 11, 29): 6, datetime.date(2016, 11, 22): 5, datetime.date(2016, 11, 4): 1, datetime.date(2016, 11, 14): 1, datetime.date(2016, 11, 24): 1, datetime.date(2016, 11, 26): 1, datetime.date(2016, 11, 1): 0, datetime.date(2016, 11, 5): 0, datetime.date(2016, 11, 6): 0, datetime.date(2016, 11, 8): 0, datetime.date(2016, 11, 11): 0, datetime.date(2016, 11, 15): 0, datetime.date(2016, 11, 16): 0, datetime.date(2016, 11, 18): 0, datetime.date(2016, 11, 19): 0, datetime.date(2016, 11, 21): 0, datetime.date(2016, 11, 25): 0, datetime.date(2016, 11, 28): 0}), region_dataset_counts=Counter({'30SWF': 7, '33STB': 7, '29SQA': 6, '29SQV': 6, '30STE': 6, '30STF': 6, '30STG': 6, '30SUF': 6, '30SUG': 6, '30SVE': 6, '30SVF': 6, '30SWE': 6, '30SWG': 6, '30SXG': 6, '30SYG': 6, '32SQF': 6, '32SQG': 6, '33STA': 6, '33STV': 5, '29SPA': 4, '30SXF': 4, '29SQB': 3, '30SVG': 3, '33SUV': 3, '30SYF': 1}), timeline_period='day', time_range=Range(begin=datetime.datetime(2016, 11, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin')), end=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin'))), footprint_geometry=<shapely.geometry.multipolygon.MultiPolygon object at 0x7f9b9133c860>, footprint_crs='EPSG:3577', footprint_count=133, newest_dataset_creation_time=datetime.datetime(2016, 11, 30, 11, 10, 1, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), crses={'EPSG:32629', 'EPSG:32633', 'EPSG:32630', 'EPSG:32632'}, size_bytes=None, summary_gen_time=datetime.datetime(2020, 12, 21, 5, 9, 46, 1630, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))), TimePeriodOverview(dataset_count=397, timeline_dataset_counts=Counter({datetime.date(2016, 12, 31): 23, datetime.date(2016, 12, 11): 21, datetime.date(2016, 12, 14): 20, datetime.date(2016, 12, 24): 20, datetime.date(2016, 12, 30): 20, datetime.date(2016, 12, 7): 19, datetime.date(2016, 12, 17): 19, datetime.date(2016, 12, 27): 19, datetime.date(2016, 12, 10): 17, datetime.date(2016, 12, 13): 17, datetime.date(2016, 12, 20): 17, datetime.date(2016, 12, 21): 17, datetime.date(2016, 12, 8): 14, datetime.date(2016, 12, 12): 14, datetime.date(2016, 12, 18): 14, datetime.date(2016, 12, 22): 14, datetime.date(2016, 12, 23): 14, datetime.date(2016, 12, 15): 13, datetime.date(2016, 12, 25): 13, datetime.date(2016, 12, 9): 11, datetime.date(2016, 12, 19): 11, datetime.date(2016, 12, 29): 11, datetime.date(2016, 12, 3): 9, datetime.date(2016, 12, 6): 8, datetime.date(2016, 12, 16): 8, datetime.date(2016, 12, 26): 8, datetime.date(2016, 12, 2): 5, datetime.date(2016, 12, 4): 1, datetime.date(2016, 12, 1): 0, datetime.date(2016, 12, 5): 0, datetime.date(2016, 12, 28): 0}), region_dataset_counts=Counter({'29SQV': 7, '30STE': 7, '29SNV': 6, '29SPA': 6, '29SPU': 6, '29SPV': 6, '29SQA': 6, '30STF': 6, '30STG': 6, '30SUE': 6, '30SUF': 6, '30SUG': 6, '30SVE': 6, '30SVF': 6, '30SWE': 6, '30SWF': 6, '30SWG': 6, '30SXG': 6, '30SYG': 6, '31SDA': 6, '31SDB': 6, '31SEA': 6, '31SEB': 6, '31SFA': 6, '31SGA': 6, '32SQF': 6, '32SQG': 6, '33STA': 6, '33STB': 6, '33STV': 6, '33SVU': 6, '33SWU': 6, '34SEC': 6, '34SFC': 6, '35SMS': 6, '35SNS': 6, '29SNU': 5, '30SXE': 5, '30SYE': 5, '30SYF': 5, '31SBA': 5, '31SBB': 5, '31SBV': 5, '31SCA': 5, '31SCB': 5, '31SCV': 5, '31SDV': 5, '31SFB': 5, '31SFV': 5, '31SGB': 5, '31SGV': 5, '32SKG': 5, '32SQE': 5, '33STU': 5, '33SUV': 5, '34SGC': 5, '35SKT': 5, '32SKE': 4, '32SLE': 4, '32SLF': 4, '32SLG': 4, '32SMF': 4, '32SMG': 4, '32SNE': 4, '32SNF': 4, '32SNG': 4, '32SPE': 4, '32SPF': 4, '32SPG': 4, '29SMU': 3, '29SQB': 3, '30SVG': 3, '30SXF': 3, '31SEV': 3, '33SUU': 3, '32SKF': 2, '32SME': 2, '35SLT': 2, '31SGC': 1, '32SKH': 1}), timeline_period='day', time_range=Range(begin=datetime.datetime(2016, 12, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin')), end=datetime.datetime(2017, 1, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin'))), footprint_geometry=<shapely.geometry.multipolygon.MultiPolygon object at 0x7f9b9134b5c0>, footprint_crs='EPSG:3577', footprint_count=397, newest_dataset_creation_time=datetime.datetime(2016, 12, 31, 10, 40, 36, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), crses={'EPSG:32635', 'EPSG:32631', 'EPSG:32630', 'EPSG:32632', 'EPSG:32633', 'EPSG:32629', 'EPSG:32634'}, size_bytes=None, summary_gen_time=datetime.datetime(2020, 12, 21, 5, 9, 47, 275676, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)))]
None

```

**Comment by jeremyh** [comment]
The first exception is strange. We're filtering the list to get only valid & non-empty polygons... then we union them, and the result of the union is throwing an error because it's empty?

To debug it, we might need to print/record that list called `with_valid_geometries` when the error happens, to see what the actual input polygons are.

**Comment by pindge** [comment]
Running raw SQL

```
africa=# select st_unaryunion(footprint_geometry)from cubedash.time_overview where product_ref = 18 and footprint_geometry is not null;
africa=# select st_union(footprint_geometry)from cubedash.time_overview where product_ref = 18 and footprint_geometry is not null;
ERROR:  GEOSUnaryUnion: TopologyException: found non-noded intersection between LINESTRING (-1.02208e+07 -2.16574e+06, -1.02209e+07 -2.16559e+06) and LINESTRING (-1.02209e+07 -2.16569e+06, -1.02209e+07 -2.16564e+06) at -10220882.874018813 -2165658.6437665028
```

**Comment by pindge** [comment]
> The first exception is strange. We're filtering the list to get only valid & non-empty polygons... then we union them, and the result of the union is throwing an error because it's empty?
> 
> To debug it, we might need to print/record that list called `with_valid_geometries` when the error happens, to see what the actual input polygons are.

I can confirm this empty value is due to `buffer(0.001)`

```
  File "/code/cubedash/summary/_model.py", line 60, in add_periods
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/code/cubedash/summary/_model.py", line 60, in <listcomp>
    periods = [p for p in periods if p is not None and p.dataset_count > 0]
  File "/code/cubedash/summary/_stores.py", line 1007, in <genexpr>
    for year_ in years
  File "/code/cubedash/summary/_stores.py", line 965, in get_or_update
    force_refresh=True,
  File "/code/cubedash/summary/_stores.py", line 998, in update
    for month_ in range(1, 13)
  File "/code/cubedash/summary/_model.py", line 115, in add_periods
    print("mpolygon is empty: ", mpolygon.buffer(0.001).is_empty)
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 637, in buffer
    return geom_factory(self.impl['buffer_with_params'](self, params, distance))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
```

**Comment by pindge** [comment]
Extreme solution
```
root@ip-10-0-13-62:/code# cubedash-gen --force-refresh --refresh-stats --no-init-database s2_l2a 
/env/lib/python3.6/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Updating 1 products for LocalConfig<loaded_from=defaults, environment='default', config={'db_hostname': 'localhost', 'db_port': '5434', 'db_database': 'africa', 'db_username': 'africa', 'db_password': '***', 'index_driver': 'default', 'db_connection_timeout': '60'}>
Generating product summaries...
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
2020-12-24T03:26:25.626335Z [warning  ] summary.footprint.union        
Traceback (most recent call last):
  File "/code/cubedash/summary/_model.py", line 95, in add_periods
    shapely.ops.unary_union([p.footprint_geometry for p in with_valid_geometries]) if with_valid_geometries else None
  File "/env/lib/python3.6/site-packages/shapely/ops.py", line 154, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
TopologyException: found non-noded intersection between LINESTRING (-1.65696e+07 -6.91138e+06, -1.65696e+07 -6.91138e+06) and LINESTRING (-1.65696e+07 -6.91138e+06, -1.65696e+07 -6.91138e+06) at -16569611.5284 -6911378.0650770711
2020-12-24T03:26:43.032357Z [warning  ] summary.footprint.union.filtering 
Traceback (most recent call last):
  File "/code/cubedash/summary/_model.py", line 95, in add_periods
    shapely.ops.unary_union([p.footprint_geometry for p in with_valid_geometries]) if with_valid_geometries else None
  File "/env/lib/python3.6/site-packages/shapely/ops.py", line 154, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/cubedash/summary/_model.py", line 106, in add_periods
    if with_valid_geometries
  File "/env/lib/python3.6/site-packages/shapely/ops.py", line 154, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/env/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
original list length 95
start index 0
geom length 95
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 94
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 93
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 92
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 91
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 90
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 89
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 88
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 87
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 86
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 85
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 84
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 83
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 82
TopologyException: found non-noded intersection between LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) and LINESTRING (-1.60083e+07 -5.78532e+06, -1.60083e+07 -5.78532e+06) at -16008349.444465393 -5785319.8790948745
start index 81
geom length 81
<class 'list'>
filtered list length 80
s2_l2a done: (1723464 datasets)
done. 1/1 generated, 0 failures
Refreshing statistics...done
```

**Comment by pindge** [comment]
before using pr #254 updated state
![image](https://user-images.githubusercontent.com/24644475/104266320-845e1600-54e3-11eb-9737-833504d8c857.png)

**Comment by pindge** [comment]
fixed, 
![image](https://user-images.githubusercontent.com/24644475/104517480-2e57b280-564a-11eb-9ed9-e74aa980f178.png)
