### ISSUE TITLE
github action failing for existing code base

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#372]
```
pre-commit run -a
shed.....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

cubedash/summary/_stores.py:1570:6: B019 Use of `functools.lru_cache` or `functools.cache` on methods can lead to memory leaks. The cache may retain instance references, preventing garbage collection.
cubedash/summary/_summarise.py:232:6: B019 Use of `functools.lru_cache` or `functools.cache` on methods can lead to memory leaks. The cache may retain instance references, preventing garbage collection.

flake8-markdown..........................................................Passed
curlylint................................................................Failed
- hook id: curlylint
- exit code: 1

Traceback (most recent call last):
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/bin/curlylint", line 8, in <module>
    sys.exit(patched_main())
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 301, in patched_main
    patch_click()
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 291, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/bin/curlylint", line 8, in <module>
    sys.exit(patched_main())
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 301, in patched_main
    patch_click()
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 291, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/bin/curlylint", line 8, in <module>
    sys.exit(patched_main())
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 301, in patched_main
    patch_click()
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 291, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/bin/curlylint", line 8, in <module>
    sys.exit(patched_main())
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 301, in patched_main
    patch_click()
  File "/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/curlylint/cli.py", line 291, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repo00x8vp8z/py_env-python3/lib/python3.8/site-packages/click/__init__.py)

yamllint.................................................................Passed
check for added large files..............................................Passed
```

**Comment by omad** [comment]
Fixed in the PR, closing.
