### ISSUE TITLE
lint github ci is failing

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#380]
```
Run make lint-docker
docker-compose run explorer \
	make lint
Creating datacube-explorer_explorer_run ... 
Creating datacube-explorer_explorer_run ... done
python3 setup.py check -rms
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
    ep.load()(self)
  File "/code/.eggs/setuptools_scm-[6](https://github.com/opendatacube/datacube-explorer/runs/6620321792?check_suite_focus=true#step:5:7).4.2-py3.[8](https://github.com/opendatacube/datacube-explorer/runs/6620321792?check_suite_focus=true#step:5:9).egg/setuptools_scm/integration.py", line [10](https://github.com/opendatacube/datacube-explorer/runs/6620321792?check_suite_focus=true#step:5:11)4, in infer_version
    _assign_version(dist, config)
  File "/code/.eggs/setuptools_scm-6.4.2-py3.8.egg/setuptools_scm/integration.py", line 51, in _assign_version
    _version_missing(config)
  File "/code/.eggs/setuptools_scm-6.4.2-py3.8.egg/setuptools_scm/__init__.py", line 106, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /code.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
make: *** [Makefile:35: lint] Error 1
2
make: *** [Makefile:[13](https://github.com/opendatacube/datacube-explorer/runs/6620321792?check_suite_focus=true#step:5:14)6: lint-docker] Error 2
Error: Process completed with exit code 2.
```

**Comment by pindge** [comment]
after adding `git tag` to Make Lint, the error was

```
Run make lint-docker
docker-compose run explorer \
	make lint
Creating datacube-explorer_explorer_run ... 
Creating datacube-explorer_explorer_run ... done
git tag
fatal: unsafe repository ('/code' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /code
make: *** [Makefile:35: lint] Error 128
2
make: *** [Makefile:13[7](https://github.com/opendatacube/datacube-explorer/runs/6662165815?check_suite_focus=true#step:5:8): lint-docker] Error 2
```

**Comment by pindge** [comment]
https://github.com/actions/checkout/issues/760
