### ISSUE TITLE
Some DEA products fail summary generation

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#7]
*ls7_nbart_albers*
```
2018-02-13 10:19.12 summary.calc.done              dataset_count=5407 footprints_missing=0 product=ls7_nbart_albers time=Range(begin=datetime.datetime(2015, 12, 1, 0,
 0), end=datetime.datetime(2016, 1, 1, 0, 0))
TopologyException: found non-noded intersection between LINESTRING (147.926 -36.7029, 147.989 -36.6964) and LINESTRING (148.005 -36.6947, 147.926 -36.7029) at 147.970
41918908911 -36.698311660120893
2018-02-13 10:19.13 report.generate                product=ls7_nbart_albers
Traceback (most recent call last):
  File "dea-dashboard/cubedash/generate.py", line 32, in generate_reports
    tmp_dir
  File "dea-dashboard/cubedash/_model.py", line 211, in write_product_summary
    s = _write_year_summary(product, year, year_folder)
  File "dea-dashboard/cubedash/_model.py", line 233, in _write_year_summary
    summary = TimePeriodOverview.add_periods(summaries)
  File "dea-dashboard/cubedash/_model.py", line 111, in add_periods
    ) if with_valid_geometries else None,
  File "/opt/conda/lib/python3.6/site-packages/shapely/ops.py", line 149, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/opt/conda/lib/python3.6/site-packages/shapely/geometry/base.py", line 76, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
error
```

*ls5_pq_albers*
```
2018-02-13 08:24.11 summary.calc.done              dataset_count=0 footprints_missing=0 product=ls5_pq_albers time=Range(begin=datetime.datetime(2011, 12, 1, 0, 0), e
nd=datetime.datetime(2012, 1, 1, 0, 0))
TopologyException: found non-noded intersection between LINESTRING (150.487 -27.3808, 150.487 -27.3808) and LINESTRING (150.487 -27.3808, 150.487 -27.3808) at 150.486
89298499346 -27.380790145386491
2018-02-13 08:24.12 report.generate                product=ls5_pq_albers
Traceback (most recent call last):
  File "dea-dashboard/cubedash/generate.py", line 32, in generate_reports
    tmp_dir
  File "dea-dashboard/cubedash/_model.py", line 211, in write_product_summary
    s = _write_year_summary(product, year, year_folder)
  File "dea-dashboard/cubedash/_model.py", line 233, in _write_year_summary
    summary = TimePeriodOverview.add_periods(summaries)
  File "dea-dashboard/cubedash/_model.py", line 111, in add_periods
    ) if with_valid_geometries else None,
  File "/opt/conda/lib/python3.6/site-packages/shapely/ops.py", line 149, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/opt/conda/lib/python3.6/site-packages/shapely/geometry/base.py", line 76, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
error
```

*ls7_nbar_albers*
```
2018-02-13 09:49.31 summary.calc.done              dataset_count=5407 footprints_missing=0 product=ls7_nbar_albers time=Range(begin=datetime.datetime(2015, 12, 1, 0, 
0), end=datetime.datetime(2016, 1, 1, 0, 0))
TopologyException: found non-noded intersection between LINESTRING (145.391 -14.3784, 145.577 -14.359) and LINESTRING (145.577 -14.359, 145.212 -14.3971) at 145.44220
027752203 -14.373039579968463
2018-02-13 09:49.32 report.generate                product=ls7_nbar_albers
Traceback (most recent call last):
  File "dea-dashboard/cubedash/generate.py", line 32, in generate_reports
    tmp_dir
  File "dea-dashboard/cubedash/_model.py", line 211, in write_product_summary
    s = _write_year_summary(product, year, year_folder)
  File "dea-dashboard/cubedash/_model.py", line 233, in _write_year_summary
    summary = TimePeriodOverview.add_periods(summaries)
  File "dea-dashboard/cubedash/_model.py", line 111, in add_periods
    ) if with_valid_geometries else None,
  File "/opt/conda/lib/python3.6/site-packages/shapely/ops.py", line 149, in unary_union
    return geom_factory(lgeos.methods['unary_union'](collection))
  File "/opt/conda/lib/python3.6/site-packages/shapely/geometry/base.py", line 76, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
error
```

**Comment by jeremyh** [comment]
No longer affects dev branch.
