### ISSUE TITLE
Doesn't run against the develop branch of datacube-core

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#9]
I've just had a go at getting this running, and got it starting, but there's a crash on startup, see below.

It's built in the Docker image that has the latest code from `develop` in it.

```
[2018-04-04 03:51:14 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/code/cubedash/__init__.py", line 3, in <module>
    from . _pages import app
  File "/code/cubedash/_pages.py", line 12, in <module>
    from cubedash import _utils as utils
  File "/code/cubedash/_utils.py", line 16, in <module>
    from datacube.index.postgres._fields import RangeDocField, PgDocField
ImportError: No module named 'datacube.index.postgres'
```

**Comment by jeremyh** [comment]
Hi Alex -- thanks for the report.

Support for the next/`develop` version of the core is in branch `next-core`. 

Our current installations are all in environments that use the stable version of datacube (and the conda install instructions install a stable datacube), so it's the default target at the moment. 

Tell me if you run into problems, as it hasn't been tested as thoroughly. I've been rebasing/force-pushing to keep it up to date as a clean set of patches, but changes to core `develop` could break it again.

**Comment by alexgleith** [comment]
Ah, ok @jeremyh. I'll try with that branch.

**Comment by alexgleith** [comment]
Got another issue this time:

(Ignore all the dashboard_1 bits)

This may be an issue with out product definition?


```
dashboard_1     | [2018-04-04 04:38:15 +0000] [1] [INFO] Starting gunicorn 19.7.1
dashboard_1     | [2018-04-04 04:38:15 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
dashboard_1     | [2018-04-04 04:38:15 +0000] [1] [INFO] Using worker: sync
dashboard_1     | [2018-04-04 04:38:15 +0000] [9] [INFO] Booting worker with pid: 9
dashboard_1     | [2018-04-04 04:38:15 +0000] [10] [INFO] Booting worker with pid: 10
dashboard_1     | [2018-04-04 04:38:15 +0000] [12] [INFO] Booting worker with pid: 12
dashboard_1     | [2018-04-04 04:38:15 +0000] [21] [INFO] Booting worker with pid: 21
dashboard_1     | [2018-04-04 04:38:15 +0000] [22] [INFO] Booting worker with pid: 22
dashboard_1     | [2018-04-04 04:38:16 +0000] [9] [ERROR] invalid syntax (_utils.py, line 125)
dashboard_1     | Traceback (most recent call last):
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
dashboard_1     |     self.wsgi = self.app.wsgi()
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
dashboard_1     |     self.callable = self.load()
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
dashboard_1     |     return self.load_wsgiapp()
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
dashboard_1     |     return util.import_app(self.app_uri)
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 352, in import_app
dashboard_1     |     __import__(module)
dashboard_1     |   File "/code/cubedash/__init__.py", line 3, in <module>
dashboard_1     |     from . _pages import app
dashboard_1     |   File "/code/cubedash/_pages.py", line 12, in <module>
dashboard_1     |     from cubedash import _utils as utils
dashboard_1     |   File "/code/cubedash/_utils.py", line 125
dashboard_1     |     field: Field = product.metadata_type.dataset_fields.get(field_name)
dashboard_1     |          ^
dashboard_1     | SyntaxError: invalid syntax
dashboard_1     | [2018-04-04 04:38:16 +0000] [9] [ERROR] Exception in worker process
dashboard_1     | Traceback (most recent call last):
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
dashboard_1     |     self.wsgi = self.app.wsgi()
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
dashboard_1     |     self.callable = self.load()
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
dashboard_1     |     return self.load_wsgiapp()
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
dashboard_1     |     return util.import_app(self.app_uri)
dashboard_1     |   File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 352, in import_app
dashboard_1     |     __import__(module)
dashboard_1     |   File "/code/cubedash/__init__.py", line 3, in <module>
dashboard_1     |     from . _pages import app
dashboard_1     |   File "/code/cubedash/_pages.py", line 12, in <module>
dashboard_1     |     from cubedash import _utils as utils
dashboard_1     |   File "/code/cubedash/_utils.py", line 125
dashboard_1     |     field: Field = product.metadata_type.dataset_fields.get(field_name)
dashboard_1     |          ^
dashboard_1     | SyntaxError: invalid syntax
```

**Comment by jeremyh** [comment]
That type definition is Python 3.6 syntax. Our Conda installs (and Travis) are all using Python 3.6.

I assume the Python 3.5 you're using is the default on Ubuntu? The difference is quite minor so we could support 3.5 if needed.

**Comment by alexgleith** [comment]
I just found that.

Datacube supports version 3.5+, so I standardised on that. Never seen the type hints in Python before! Not sure what I think yet ;-)

I think supporting 3.5 would be better.

**Comment by alexgleith** [comment]
Ok, got it working. I needed to use Python 3.6 and the `next-core` branch, and also needed to change the generate command to say `python3`, but it seems happy. 

You might like to update the readme in the root to say `nohup python3 -m cubedash.generate --all &>> summary-gen.log &`

![image](https://user-images.githubusercontent.com/3445853/38339448-a4cdd1e2-38b1-11e8-80da-73edea28a6cb.png)

**Comment by jeremyh** [comment]
Closing. Datacube 1.6 is now released, and we've merged support for it into `develop`.
